import { appSchema, tableSchema } from "@nozbe/watermelondb";

export default appSchema({
  version: 1,
  tables: [
    tableSchema({
      name: "appointment_types",
      columns: [
        { name: "name_en", type: "string" },
        { name: "name_ar", type: "string", isOptional: true },
        { name: "name_fr", type: "string", isOptional: true },
        { name: "color", type: "string", isOptional: true },
      ],
    }),
    tableSchema({
      name: "locations",
      columns: [
        { name: "name_en", type: "string" },
        { name: "name_ar", type: "string", isOptional: true },
        { name: "name_fr", type: "string", isOptional: true },
      ],
    }),
    tableSchema({
      name: "patients",
      columns: [
        { name: "is_vip", type: "boolean" },
        { name: "vip_status_date", type: "number", isOptional: true },
        { name: "balance", type: "number" },
        { name: "gender", type: "string", isOptional: true },
        { name: "blood_type", type: "string", isOptional: true },
        { name: "title", type: "string", isOptional: true },
        { name: "first_name", type: "string", isOptional: true },
        { name: "father_name", type: "string", isOptional: true },
        {
          name: "last_name",
          type: "string",
          isOptional: true,
          isIndexed: true,
        },
        { name: "birth_date", type: "number", isOptional: true },
        { name: "address", type: "string", isOptional: true },
        { name: "country_code", type: "string", isOptional: true },
        { name: "currency", type: "string", isOptional: true },
        { name: "phone_number", type: "string", isOptional: true },
        { name: "email_address", type: "string", isOptional: true },
        { name: "is_active", type: "boolean", isIndexed: true },
        { name: "profile_photo", type: "string", isOptional: true },
      ],
    }),
    tableSchema({
      name: "appointments",
      columns: [
        { name: "provider_id", type: "string", isIndexed: true },
        {
          name: "patient_id",
          type: "string",
          isOptional: true,
          isIndexed: true,
        },
        { name: "type_id", type: "string", isOptional: true, isIndexed: true },
        {
          name: "location_id",
          type: "string",
          isOptional: true,
          isIndexed: true,
        },
        { name: "subject", type: "string" },
        { name: "status", type: "string", isIndexed: true },
        { name: "description", type: "string", isOptional: true },
        { name: "start_time", type: "number", isIndexed: true },
        { name: "end_time", type: "number" },
      ],
    }),
    tableSchema({
      name: "services",
      columns: [
        { name: "provider_id", type: "string", isIndexed: true },
        { name: "patient_id", type: "string", isIndexed: true },
        { name: "status", type: "string", isIndexed: true },
        { name: "code", type: "string", isOptional: true },
        { name: "name_en", type: "string" },
        { name: "name_ar", type: "string", isOptional: true },
        { name: "name_fr", type: "string", isOptional: true },
        { name: "date", type: "number", isIndexed: true },
        { name: "note", type: "string", isOptional: true },
        { name: "fee", type: "number" },
        { name: "color", type: "string", isOptional: true },
        { name: "status_color", type: "string", isOptional: true },
        { name: "posted_date", type: "number", isOptional: true },
        { name: "is_posted", type: "boolean", isIndexed: true },
      ],
    }),
    tableSchema({
      name: "payments",
      columns: [
        { name: "provider_id", type: "string", isIndexed: true },
        { name: "patient_id", type: "string", isIndexed: true },
        { name: "type", type: "string" },
        { name: "method", type: "string" },
        { name: "currency", type: "string" },
        { name: "status", type: "string", isIndexed: true },
        { name: "amount", type: "number" },
        { name: "date", type: "number", isIndexed: true },
        { name: "posted_date", type: "number", isOptional: true },
        { name: "description", type: "string", isOptional: true },
        { name: "is_posted", type: "boolean", isIndexed: true },
        { name: "is_active", type: "boolean", isIndexed: true },
      ],
    }),
    tableSchema({
      name: "recalls",
      columns: [
        { name: "provider_id", type: "string", isIndexed: true },
        { name: "patient_id", type: "string", isIndexed: true },
        { name: "service_code", type: "string", isOptional: true },
        { name: "service_name_en", type: "string" },
        { name: "service_name_ar", type: "string", isOptional: true },
        { name: "service_name_fr", type: "string", isOptional: true },
        { name: "interval", type: "number" },
        { name: "reminder_interval", type: "number" },
        { name: "date", type: "number" },
        { name: "due_date", type: "number", isIndexed: true },
        { name: "note", type: "string", isOptional: true },
        { name: "is_active", type: "boolean", isIndexed: true },
      ],
    }),
  ],
});
